spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: Desktoputo98ah
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true